server:
  port: 8082

product.client:
  url: http://localhost:8081

management:
  endpoints:
    web.exposure.include: '*'
    health.show-details: always

resilience4j.circuitbreaker:
  instances:
    products-get-id:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
        - org.springframework.web.client.HttpClientErrorException
      ignoreExceptions:

    get:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 6
      ringBufferSizeInHalfOpenState: 4
      waitDurationInOpenState: 20s
      failureRateThreshold: 60

resilience4j.ratelimiter:
  instances:
    products-get-ratelimiter:
      limitForPeriod: 1
      limitRefreshPeriod: 5s #ms
      timeoutDuration: 0s

resilience4j.retry:
  instances:
#    ratingService:
#      maxRetryAttempts: 3
#      waitDuration: 5s
#      retryExceptions:
#        - org.springframework.web.client.HttpServerErrorException
#      ignoreExceptions:
#        - org.springframework.web.client.HttpClientErrorException
    get-retry:
      maxRetryAttempts: 3
      waitDuration: 10s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException

#resilience4j.bulkhead:
#  instances:
#    get:
#      max-concurrent-calls: 10
#      maxWaitDuration: 10ms